---
  name: Terraform CI/CD
  
  on:
    workflow_dispatch:
  
  permissions:
    id-token: write # This is required for requesting the JWT
    contents: read # This is required for actions/checkout
    actions: read
  
  jobs:
    terraform:
      name: Terraform
      runs-on: ubuntu-latest
      environment: production
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_USE_OIDC: true
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 1
        - name: Azure login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_wrapper: false
            terraform_version: ${{ env.TERRAFORM_VERSION }}
        - name: Terraform init
          run: terraform init -backend-config="subscription_id=8d9d28aa-56ff-4d4c-ab85-a94198d8ad0e" -backend-config="resource_group_name=rg-infra-prod-001" -backend-config="storage_account_name=terraformstoragefesti" -backend-config="container_name=statefiles" -backend-config="key=CAF/terraform.tfstate"
        - name: Terraform plan
          run: terraform plan -refresh-only --var-file="data.tfvars" 
  